In [155]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')
%matplotlib inline

In [ ]:
df=pd.read_csv(r'C:\Users\ys136\Desktop\Data Science\End to End ML Projects\Thyroid_Prediction_System\Notebooks\data\hypothyroid.csv')

In [157]:
df.head()

,age,sex,on_thyroxine,query_on_thyroxine,on_antithyroid_medication,sick,pregnant,thyroid_surgery,I131_treatment,query_hypothyroid,query_hyperthyroid,lithium,goitre,tumor,hypopituitary,psych,TSH_measured,TSH,T3_measured,T3,TT4_measured,TT4,T4U_measured,T4U,FTI_measured,FTI,TBG_measured,TBG,referral_source,Class
0,41,F,f,f,f,f,f,f,f,f,f,f,f,f,f,f,t,1.3,t,2.5,t,125,t,1.14,t,109,f,?,SVHC,negative
1,23,F,f,f,f,f,f,f,f,f,f,f,f,f,f,f,t,4.1,t,2,t,102,f,?,f,?,f,?,other,negative
2,46,M,f,f,f,f,f,f,f,f,f,f,f,f,f,f,t,0.98,f,?,t,109,t,0.91,t,120,f,?,other,negative
3,70,F,t,f,f,f,f,f,f,f,f,f,f,f,f,f,t,0.16,t,1.9,t,175,f,?,f,?,f,?,other,negative
4,70,F,f,f,f,f,f,f,f,f,f,f,f,f,f,f,t,0.72,t,1.2,t,61,t,0.87,t,70,f,?,SVI,negative

In [158]:
df['Class'].value_counts()

Class
negative                   3481
compensated_hypothyroid     194
primary_hypothyroid          95
secondary_hypothyroid         2
Name: count, dtype: int64

In [159]:
df_minority=df[df['Class']=='secondary_hypothyroid']
df_minority1=df[df['Class']=='primary_hypothyroid']
df_minority2=df[df['Class']=='compensated_hypothyroid']

In [160]:
df_majority=df[df['Class']=='negative']

In [161]:
len(df_majority)

3481

In [162]:
from sklearn.utils import resample

In [163]:
# df_minority_upsampling=resample(df_minority,replace=True,n_samples=len(df_majority),random_state=42)
# df_minority1_upsampling=resample(df_minority1,replace=True,n_samples=len(df_majority),random_state=42)
# df_minority2_upsampling=resample(df_minority2,replace=True,n_samples=len(df_majority),random_state=42)

In [164]:
# df=pd.concat([df_minority_upsampling,df_minority1_upsampling,df_minority2_upsampling,df_majority])

In [165]:
from imblearn.over_sampling import SMOTE

In [166]:
resample=SMOTE()

In [167]:
df.columns

Index(['age', 'sex', 'on_thyroxine', 'query_on_thyroxine',
       'on_antithyroid_medication', 'sick', 'pregnant', 'thyroid_surgery',
       'I131_treatment', 'query_hypothyroid', 'query_hyperthyroid', 'lithium',
       'goitre', 'tumor', 'hypopituitary', 'psych', 'TSH_measured', 'TSH',
       'T3_measured', 'T3', 'TT4_measured', 'TT4', 'T4U_measured', 'T4U',
       'FTI_measured', 'FTI', 'TBG_measured', 'TBG', 'referral_source',
       'Class'],
      dtype='object')

In [168]:
df.Class.value_counts()

Class
negative                   3481
compensated_hypothyroid     194
primary_hypothyroid          95
secondary_hypothyroid         2
Name: count, dtype: int64

In [169]:
df.isnull().sum()

age                          0
sex                          0
on_thyroxine                 0
query_on_thyroxine           0
on_antithyroid_medication    0
sick                         0
pregnant                     0
thyroid_surgery              0
I131_treatment               0
query_hypothyroid            0
query_hyperthyroid           0
lithium                      0
goitre                       0
tumor                        0
hypopituitary                0
psych                        0
TSH_measured                 0
TSH                          0
T3_measured                  0
T3                           0
TT4_measured                 0
TT4                          0
T4U_measured                 0
T4U                          0
FTI_measured                 0
FTI                          0
TBG_measured                 0
TBG                          0
referral_source              0
Class                        0
dtype: int64

In [170]:
df.duplicated().sum()

61

In [171]:
df.describe(include='all')

,age,sex,on_thyroxine,query_on_thyroxine,on_antithyroid_medication,sick,pregnant,thyroid_surgery,I131_treatment,query_hypothyroid,query_hyperthyroid,lithium,goitre,tumor,hypopituitary,psych,TSH_measured,TSH,T3_measured,T3,TT4_measured,TT4,T4U_measured,T4U,FTI_measured,FTI,TBG_measured,TBG,referral_source,Class
count,3772,3772,3772,3772,3772,3772,3772,3772,3772,3772,3772,3772,3772,3772,3772,3772,3772,3772,3772,3772,3772,3772,3772,3772,3772,3772,3772,3772,3772,3772
unique,94,3,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,288,2,70,2,242,2,147,2,235,1,1,5,4
top,59,F,f,f,f,f,f,f,f,f,f,f,f,f,f,f,t,?,t,?,t,?,t,?,t,?,f,?,other,negative
freq,95,2480,3308,3722,3729,3625,3719,3719,3713,3538,3535,3754,3738,3676,3771,3588,3403,369,3003,769,3541,231,3385,387,3387,385,3772,3772,2201,3481

In [172]:
for column in df.columns:
    count=df[column][df[column]=='?'].count()
    if count!=0:
        print(column,df[column][df[column]=='?'].count())

age 1
sex 150
TSH 369
T3 769
TT4 231
T4U 387
FTI 385
TBG 3772

In [173]:
for column in df.columns:
    count=df[column][df[column]=='?'].count()
    if count!=0:
        df[column]=df[column].replace('?',np.nan)

In [174]:
for column in df.columns:
    count=df[column][df[column]=='?'].count()
    if count==0:
        print(column,df[column][df[column]=='?'].count())

age 0
sex 0
on_thyroxine 0
query_on_thyroxine 0
on_antithyroid_medication 0
sick 0
pregnant 0
thyroid_surgery 0
I131_treatment 0
query_hypothyroid 0
query_hyperthyroid 0
lithium 0
goitre 0
tumor 0
hypopituitary 0
psych 0
TSH_measured 0
TSH 0
T3_measured 0
T3 0
TT4_measured 0
TT4 0
T4U_measured 0
T4U 0
FTI_measured 0
FTI 0
TBG_measured 0
TBG 0
referral_source 0
Class 0

In [175]:
df.isnull().sum()

age                             1
sex                           150
on_thyroxine                    0
query_on_thyroxine              0
on_antithyroid_medication       0
sick                            0
pregnant                        0
thyroid_surgery                 0
I131_treatment                  0
query_hypothyroid               0
query_hyperthyroid              0
lithium                         0
goitre                          0
tumor                           0
hypopituitary                   0
psych                           0
TSH_measured                    0
TSH                           369
T3_measured                     0
T3                            769
TT4_measured                    0
TT4                           231
T4U_measured                    0
T4U                           387
FTI_measured                    0
FTI                           385
TBG_measured                    0
TBG                          3772
referral_source                 0
Class                           0
dtype: int64

In [176]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3772 entries, 0 to 3771
Data columns (total 30 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   age                        3771 non-null   object
 1   sex                        3622 non-null   object
 2   on_thyroxine               3772 non-null   object
 3   query_on_thyroxine         3772 non-null   object
 4   on_antithyroid_medication  3772 non-null   object
 5   sick                       3772 non-null   object
 6   pregnant                   3772 non-null   object
 7   thyroid_surgery            3772 non-null   object
 8   I131_treatment             3772 non-null   object
 9   query_hypothyroid          3772 non-null   object
 10  query_hyperthyroid         3772 non-null   object
 11  lithium                    3772 non-null   object
 12  goitre                     3772 non-null   object
 13  tumor                      3772 non-null   object
 14  hypopituitary              3772 non-null   object
 15  psych                      3772 non-null   object
 16  TSH_measured               3772 non-null   object
 17  TSH                        3403 non-null   object
 18  T3_measured                3772 non-null   object
 19  T3                         3003 non-null   object
 20  TT4_measured               3772 non-null   object
 21  TT4                        3541 non-null   object
 22  T4U_measured               3772 non-null   object
 23  T4U                        3385 non-null   object
 24  FTI_measured               3772 non-null   object
 25  FTI                        3387 non-null   object
 26  TBG_measured               3772 non-null   object
 27  TBG                        0 non-null      float64
 28  referral_source            3772 non-null   object
 29  Class                      3772 non-null   object
dtypes: float64(1), object(29)
memory usage: 884.2+ KB

In [177]:
df.head()

,age,sex,on_thyroxine,query_on_thyroxine,on_antithyroid_medication,sick,pregnant,thyroid_surgery,I131_treatment,query_hypothyroid,query_hyperthyroid,lithium,goitre,tumor,hypopituitary,psych,TSH_measured,TSH,T3_measured,T3,TT4_measured,TT4,T4U_measured,T4U,FTI_measured,FTI,TBG_measured,TBG,referral_source,Class
0,41,F,f,f,f,f,f,f,f,f,f,f,f,f,f,f,t,1.3,t,2.5,t,125,t,1.14,t,109,f,NaN,SVHC,negative
1,23,F,f,f,f,f,f,f,f,f,f,f,f,f,f,f,t,4.1,t,2,t,102,f,NaN,f,NaN,f,NaN,other,negative
2,46,M,f,f,f,f,f,f,f,f,f,f,f,f,f,f,t,0.98,f,NaN,t,109,t,0.91,t,120,f,NaN,other,negative
3,70,F,t,f,f,f,f,f,f,f,f,f,f,f,f,f,t,0.16,t,1.9,t,175,f,NaN,f,NaN,f,NaN,other,negative
4,70,F,f,f,f,f,f,f,f,f,f,f,f,f,f,f,t,0.72,t,1.2,t,61,t,0.87,t,70,f,NaN,SVI,negative

In [178]:
df['sex']=df['sex'].map({"F":0,"M":1})

In [179]:
for col in df.columns:
    if len(df[col].unique())==2:
        df[col]=df[col].map({'t':1,'f':0})

In [180]:
df.head()

,age,sex,on_thyroxine,query_on_thyroxine,on_antithyroid_medication,sick,pregnant,thyroid_surgery,I131_treatment,query_hypothyroid,query_hyperthyroid,lithium,goitre,tumor,hypopituitary,psych,TSH_measured,TSH,T3_measured,T3,TT4_measured,TT4,T4U_measured,T4U,FTI_measured,FTI,TBG_measured,TBG,referral_source,Class
0,41,0.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1.3,1,2.5,1,125,1,1.14,1,109,f,NaN,SVHC,negative
1,23,0.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,4.1,1,2,1,102,0,NaN,0,NaN,f,NaN,other,negative
2,46,1.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0.98,0,NaN,1,109,1,0.91,1,120,f,NaN,other,negative
3,70,0.0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0.16,1,1.9,1,175,0,NaN,0,NaN,f,NaN,other,negative
4,70,0.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0.72,1,1.2,1,61,1,0.87,1,70,f,NaN,SVI,negative

In [181]:
pd.set_option('display.max_columns',None)

In [182]:
df.head()

,age,sex,on_thyroxine,query_on_thyroxine,on_antithyroid_medication,sick,pregnant,thyroid_surgery,I131_treatment,query_hypothyroid,query_hyperthyroid,lithium,goitre,tumor,hypopituitary,psych,TSH_measured,TSH,T3_measured,T3,TT4_measured,TT4,T4U_measured,T4U,FTI_measured,FTI,TBG_measured,TBG,referral_source,Class
0,41,0.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1.3,1,2.5,1,125,1,1.14,1,109,f,NaN,SVHC,negative
1,23,0.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,4.1,1,2,1,102,0,NaN,0,NaN,f,NaN,other,negative
2,46,1.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0.98,0,NaN,1,109,1,0.91,1,120,f,NaN,other,negative
3,70,0.0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0.16,1,1.9,1,175,0,NaN,0,NaN,f,NaN,other,negative
4,70,0.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0.72,1,1.2,1,61,1,0.87,1,70,f,NaN,SVI,negative

In [183]:
df['TBG'].unique()

array([nan])

In [203]:
df.Class.value_counts()

Class
1    3481
0    3481
2    3481
3    3481
Name: count, dtype: int64

In [184]:
df.drop(labels='TBG',inplace=True,axis=1)

In [185]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3772 entries, 0 to 3771
Data columns (total 29 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   age                        3771 non-null   object
 1   sex                        3622 non-null   float64
 2   on_thyroxine               3772 non-null   int64
 3   query_on_thyroxine         3772 non-null   int64
 4   on_antithyroid_medication  3772 non-null   int64
 5   sick                       3772 non-null   int64
 6   pregnant                   3772 non-null   int64
 7   thyroid_surgery            3772 non-null   int64
 8   I131_treatment             3772 non-null   int64
 9   query_hypothyroid          3772 non-null   int64
 10  query_hyperthyroid         3772 non-null   int64
 11  lithium                    3772 non-null   int64
 12  goitre                     3772 non-null   int64
 13  tumor                      3772 non-null   int64
 14  hypopituitary              3772 non-null   int64
 15  psych                      3772 non-null   int64
 16  TSH_measured               3772 non-null   int64
 17  TSH                        3403 non-null   object
 18  T3_measured                3772 non-null   int64
 19  T3                         3003 non-null   object
 20  TT4_measured               3772 non-null   int64
 21  TT4                        3541 non-null   object
 22  T4U_measured               3772 non-null   int64
 23  T4U                        3385 non-null   object
 24  FTI_measured               3772 non-null   int64
 25  FTI                        3387 non-null   object
 26  TBG_measured               3772 non-null   object
 27  referral_source            3772 non-null   object
 28  Class                      3772 non-null   object
dtypes: float64(1), int64(19), object(9)
memory usage: 854.7+ KB

In [186]:
df.drop(['TSH_measured','T3_measured','TT4_measured','T4U_measured','FTI_measured','TBG_measured'],axis =1,inplace=True)

In [187]:
df.head()

,age,sex,on_thyroxine,query_on_thyroxine,on_antithyroid_medication,sick,pregnant,thyroid_surgery,I131_treatment,query_hypothyroid,query_hyperthyroid,lithium,goitre,tumor,hypopituitary,psych,TSH,T3,TT4,T4U,FTI,referral_source,Class
0,41,0.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1.3,2.5,125,1.14,109,SVHC,negative
1,23,0.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,4.1,2,102,NaN,NaN,other,negative
2,46,1.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.98,NaN,109,0.91,120,other,negative
3,70,0.0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0.16,1.9,175,NaN,NaN,other,negative
4,70,0.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.72,1.2,61,0.87,70,SVI,negative

In [188]:
df['age']=df['age'].astype(float)

In [189]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3772 entries, 0 to 3771
Data columns (total 23 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   age                        3771 non-null   float64
 1   sex                        3622 non-null   float64
 2   on_thyroxine               3772 non-null   int64
 3   query_on_thyroxine         3772 non-null   int64
 4   on_antithyroid_medication  3772 non-null   int64
 5   sick                       3772 non-null   int64
 6   pregnant                   3772 non-null   int64
 7   thyroid_surgery            3772 non-null   int64
 8   I131_treatment             3772 non-null   int64
 9   query_hypothyroid          3772 non-null   int64
 10  query_hyperthyroid         3772 non-null   int64
 11  lithium                    3772 non-null   int64
 12  goitre                     3772 non-null   int64
 13  tumor                      3772 non-null   int64
 14  hypopituitary              3772 non-null   int64
 15  psych                      3772 non-null   int64
 16  TSH                        3403 non-null   object
 17  T3                         3003 non-null   object
 18  TT4                        3541 non-null   object
 19  T4U                        3385 non-null   object
 20  FTI                        3387 non-null   object
 21  referral_source            3772 non-null   object
 22  Class                      3772 non-null   object
dtypes: float64(2), int64(14), object(7)
memory usage: 677.9+ KB

In [190]:
from sklearn.preprocessing import LabelEncoder

In [191]:
encoder=LabelEncoder()

In [192]:
df['Class']=encoder.fit_transform(df['Class'])

In [193]:
df.columns

Index(['age', 'sex', 'on_thyroxine', 'query_on_thyroxine',
       'on_antithyroid_medication', 'sick', 'pregnant', 'thyroid_surgery',
       'I131_treatment', 'query_hypothyroid', 'query_hyperthyroid', 'lithium',
       'goitre', 'tumor', 'hypopituitary', 'psych', 'TSH', 'T3', 'TT4', 'T4U',
       'FTI', 'referral_source', 'Class'],
      dtype='object')

In [194]:
X=df.drop(labels='Class',axis=1)
y=df['Class']

In [195]:
X=pd.get_dummies(data=X,columns=['referral_source'])

In [196]:
X.head()

,age,sex,on_thyroxine,query_on_thyroxine,on_antithyroid_medication,sick,pregnant,thyroid_surgery,I131_treatment,query_hypothyroid,query_hyperthyroid,lithium,goitre,tumor,hypopituitary,psych,TSH,T3,TT4,T4U,FTI,referral_source_STMW,referral_source_SVHC,referral_source_SVHD,referral_source_SVI,referral_source_other
0,41.0,0.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1.3,2.5,125,1.14,109,False,True,False,False,False
1,23.0,0.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,4.1,2,102,NaN,NaN,False,False,False,False,True
2,46.0,1.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.98,NaN,109,0.91,120,False,False,False,False,True
3,70.0,0.0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0.16,1.9,175,NaN,NaN,False,False,False,False,True
4,70.0,0.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.72,1.2,61,0.87,70,False,False,False,True,False

In [199]:
from imblearn.over_sampling import RandomOverSampler
os=RandomOverSampler(random_state=42)
X,y=os.fit_resample(X,y)

In [200]:
df=pd.concat([X,y],axis=1)

In [201]:
df.head()

,age,sex,on_thyroxine,query_on_thyroxine,on_antithyroid_medication,sick,pregnant,thyroid_surgery,I131_treatment,query_hypothyroid,query_hyperthyroid,lithium,goitre,tumor,hypopituitary,psych,TSH,T3,TT4,T4U,FTI,referral_source_STMW,referral_source_SVHC,referral_source_SVHD,referral_source_SVI,referral_source_other,Class
0,41.0,0.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1.3,2.5,125,1.14,109,False,True,False,False,False,1
1,23.0,0.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,4.1,2,102,NaN,NaN,False,False,False,False,True,1
2,46.0,1.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.98,NaN,109,0.91,120,False,False,False,False,True,1
3,70.0,0.0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0.16,1.9,175,NaN,NaN,False,False,False,False,True,1
4,70.0,0.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.72,1.2,61,0.87,70,False,False,False,True,False,1

In [ ]:
df.to_csv(r'C:\Users\ys136\Desktop\Data Science\End to End ML Projects\Thyroid_Prediction_System\Notebooks\data\data.csv')

In [126]:
categorical_columns =X.columns[X.dtypes=='O']
numerical_columns=X.columns[X.dtypes!='O']

In [127]:
numerical_columns

Index(['age', 'sex', 'on_thyroxine', 'query_on_thyroxine',
       'on_antithyroid_medication', 'sick', 'pregnant', 'thyroid_surgery',
       'I131_treatment', 'query_hypothyroid', 'query_hyperthyroid', 'lithium',
       'goitre', 'tumor', 'hypopituitary', 'psych', 'referral_source_STMW',
       'referral_source_SVHC', 'referral_source_SVHD', 'referral_source_SVI',
       'referral_source_other'],
      dtype='object')

In [128]:
categorical_columns

Index(['TSH', 'T3', 'TT4', 'T4U', 'FTI'], dtype='object')

In [129]:
numerical_columns

Index(['age', 'sex', 'on_thyroxine', 'query_on_thyroxine',
       'on_antithyroid_medication', 'sick', 'pregnant', 'thyroid_surgery',
       'I131_treatment', 'query_hypothyroid', 'query_hyperthyroid', 'lithium',
       'goitre', 'tumor', 'hypopituitary', 'psych', 'referral_source_STMW',
       'referral_source_SVHC', 'referral_source_SVHD', 'referral_source_SVI',
       'referral_source_other'],
      dtype='object')

In [130]:
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler
from sklearn.impute import SimpleImputer
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline

In [131]:
numerical_pipeline=Pipeline(
    steps=[
        ('imputer', SimpleImputer(strategy='mean')),
        ('scaler', StandardScaler()),


    ]
)
categorical_pipeline=Pipeline(
    steps=[
        ('imputer',SimpleImputer(strategy='most_frequent')),
        ('scaler',StandardScaler()),
        

    ]
)

In [132]:
preprocessor=ColumnTransformer(
    transformers=[
        ('numerical_pipeline',numerical_pipeline,numerical_columns),
        ('categorical_pipeline',categorical_pipeline,categorical_columns)
    ]
)

In [133]:
from sklearn.model_selection import train_test_split

In [134]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.30,random_state=30)

In [135]:
X_train.head()

,age,sex,on_thyroxine,query_on_thyroxine,on_antithyroid_medication,sick,pregnant,thyroid_surgery,I131_treatment,query_hypothyroid,query_hyperthyroid,lithium,goitre,tumor,hypopituitary,psych,TSH,T3,TT4,T4U,FTI,referral_source_STMW,referral_source_SVHC,referral_source_SVHD,referral_source_SVI,referral_source_other
3716,75.0,1.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,2,NaN,74,1.05,70,False,False,False,False,True
9050,77.0,0.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,23,0.5,33,0.67,49,False,False,False,True,False
2271,47.0,1.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,2.4,2.2,143,0.92,154,False,False,False,True,False
8365,60.0,0.0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,183,1.1,45,0.97,46,False,False,False,False,True
9417,45.0,0.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,24,NaN,NaN,NaN,NaN,False,False,False,True,False

In [136]:
X_train=pd.DataFrame(preprocessor.fit_transform(X_train),columns=preprocessor.get_feature_names_out())

In [137]:
X_train.head()

,numerical_pipeline__age,numerical_pipeline__sex,numerical_pipeline__on_thyroxine,numerical_pipeline__query_on_thyroxine,numerical_pipeline__on_antithyroid_medication,numerical_pipeline__sick,numerical_pipeline__pregnant,numerical_pipeline__thyroid_surgery,numerical_pipeline__I131_treatment,numerical_pipeline__query_hypothyroid,numerical_pipeline__query_hyperthyroid,numerical_pipeline__lithium,numerical_pipeline__goitre,numerical_pipeline__tumor,numerical_pipeline__hypopituitary,numerical_pipeline__psych,numerical_pipeline__referral_source_STMW,numerical_pipeline__referral_source_SVHC,numerical_pipeline__referral_source_SVHD,numerical_pipeline__referral_source_SVI,numerical_pipeline__referral_source_other,categorical_pipeline__TSH,categorical_pipeline__T3,categorical_pipeline__TT4,categorical_pipeline__T4U,categorical_pipeline__FTI
0,1.514954,1.460376,-0.246203,-0.091546,-0.060035,-0.152322,-0.058288,-0.098155,-0.117175,-0.511327,-0.198652,-0.050712,-0.044196,-0.137561,-0.01013,-0.152322,-0.151616,-0.208224,-0.077374,-0.569214,0.677643,-0.374600,-0.511564,0.159041,0.474300,-0.065909
1,1.633652,-0.705681,-0.246203,-0.091546,-0.060035,-0.152322,-0.058288,-0.098155,-0.117175,-0.511327,-0.198652,-0.050712,-0.044196,-0.137561,-0.01013,-0.152322,-0.151616,-0.208224,-0.077374,1.756808,-1.475703,-0.052459,-1.423446,-0.841131,-1.806900,-0.646792
2,-0.146823,1.460376,-0.246203,-0.091546,-0.060035,-0.152322,-0.058288,-0.098155,-0.117175,-0.511327,-0.198652,-0.050712,-0.044196,-0.137561,-0.01013,-0.152322,-0.151616,-0.208224,-0.077374,1.756808,-1.475703,-0.368464,0.791125,1.842256,-0.306110,2.257624
3,0.624716,-0.705681,-0.246203,-0.091546,-0.060035,-0.152322,-0.058288,-0.098155,-0.117175,1.955697,-0.198652,-0.050712,-0.044196,-0.137561,-0.01013,-0.152322,-0.151616,-0.208224,-0.077374,-0.569214,0.677643,2.401947,-0.641833,-0.548398,-0.005953,-0.729775
4,-0.265521,-0.705681,-0.246203,-0.091546,-0.060035,-0.152322,-0.058288,-0.098155,-0.117175,-0.511327,-0.198652,-0.050712,-0.044196,-0.137561,-0.01013,-0.152322,-0.151616,-0.208224,-0.077374,1.756808,-1.475703,-0.037119,-0.511564,-0.475214,-0.486205,-0.508486

In [138]:
X_test=pd.DataFrame(preprocessor.transform(X_test),columns=preprocessor.get_feature_names_out())

In [139]:
X_train.head()

,numerical_pipeline__age,numerical_pipeline__sex,numerical_pipeline__on_thyroxine,numerical_pipeline__query_on_thyroxine,numerical_pipeline__on_antithyroid_medication,numerical_pipeline__sick,numerical_pipeline__pregnant,numerical_pipeline__thyroid_surgery,numerical_pipeline__I131_treatment,numerical_pipeline__query_hypothyroid,numerical_pipeline__query_hyperthyroid,numerical_pipeline__lithium,numerical_pipeline__goitre,numerical_pipeline__tumor,numerical_pipeline__hypopituitary,numerical_pipeline__psych,numerical_pipeline__referral_source_STMW,numerical_pipeline__referral_source_SVHC,numerical_pipeline__referral_source_SVHD,numerical_pipeline__referral_source_SVI,numerical_pipeline__referral_source_other,categorical_pipeline__TSH,categorical_pipeline__T3,categorical_pipeline__TT4,categorical_pipeline__T4U,categorical_pipeline__FTI
0,1.514954,1.460376,-0.246203,-0.091546,-0.060035,-0.152322,-0.058288,-0.098155,-0.117175,-0.511327,-0.198652,-0.050712,-0.044196,-0.137561,-0.01013,-0.152322,-0.151616,-0.208224,-0.077374,-0.569214,0.677643,-0.374600,-0.511564,0.159041,0.474300,-0.065909
1,1.633652,-0.705681,-0.246203,-0.091546,-0.060035,-0.152322,-0.058288,-0.098155,-0.117175,-0.511327,-0.198652,-0.050712,-0.044196,-0.137561,-0.01013,-0.152322,-0.151616,-0.208224,-0.077374,1.756808,-1.475703,-0.052459,-1.423446,-0.841131,-1.806900,-0.646792
2,-0.146823,1.460376,-0.246203,-0.091546,-0.060035,-0.152322,-0.058288,-0.098155,-0.117175,-0.511327,-0.198652,-0.050712,-0.044196,-0.137561,-0.01013,-0.152322,-0.151616,-0.208224,-0.077374,1.756808,-1.475703,-0.368464,0.791125,1.842256,-0.306110,2.257624
3,0.624716,-0.705681,-0.246203,-0.091546,-0.060035,-0.152322,-0.058288,-0.098155,-0.117175,1.955697,-0.198652,-0.050712,-0.044196,-0.137561,-0.01013,-0.152322,-0.151616,-0.208224,-0.077374,-0.569214,0.677643,2.401947,-0.641833,-0.548398,-0.005953,-0.729775
4,-0.265521,-0.705681,-0.246203,-0.091546,-0.060035,-0.152322,-0.058288,-0.098155,-0.117175,-0.511327,-0.198652,-0.050712,-0.044196,-0.137561,-0.01013,-0.152322,-0.151616,-0.208224,-0.077374,1.756808,-1.475703,-0.037119,-0.511564,-0.475214,-0.486205,-0.508486

In [140]:
from sklearn.feature_selection import mutual_info_classif

In [141]:
mutual=mutual_info_classif(X_train,y_train)

In [142]:
mutual

array([6.67983033e-01, 2.99338504e-02, 3.51420276e-02, 1.33857431e-02,
       3.92917969e-03, 1.77113539e-02, 9.59262778e-03, 1.64694034e-02,
       9.44949988e-03, 9.00646190e-02, 8.51561672e-03, 0.00000000e+00,
       4.48558692e-03, 4.24712764e-03, 6.22541870e-04, 2.02723814e-02,
       1.78310543e-03, 2.32615741e-02, 9.41709499e-03, 9.05772879e-02,
       1.07705192e-01, 1.17348113e+00, 4.63600576e-01, 9.40761087e-01,
       5.15868304e-01, 8.90620267e-01])

In [143]:
mutual=pd.Series(mutual)
mutual.index=X_train.columns
mutual.sort_values(ascending=False)

categorical_pipeline__TSH                        1.173481
categorical_pipeline__TT4                        0.940761
categorical_pipeline__FTI                        0.890620
numerical_pipeline__age                          0.667983
categorical_pipeline__T4U                        0.515868
categorical_pipeline__T3                         0.463601
numerical_pipeline__referral_source_other        0.107705
numerical_pipeline__referral_source_SVI          0.090577
numerical_pipeline__query_hypothyroid            0.090065
numerical_pipeline__on_thyroxine                 0.035142
numerical_pipeline__sex                          0.029934
numerical_pipeline__referral_source_SVHC         0.023262
numerical_pipeline__psych                        0.020272
numerical_pipeline__sick                         0.017711
numerical_pipeline__thyroid_surgery              0.016469
numerical_pipeline__query_on_thyroxine           0.013386
numerical_pipeline__pregnant                     0.009593
numerical_pipeline__I131_treatment               0.009449
numerical_pipeline__referral_source_SVHD         0.009417
numerical_pipeline__query_hyperthyroid           0.008516
numerical_pipeline__goitre                       0.004486
numerical_pipeline__tumor                        0.004247
numerical_pipeline__on_antithyroid_medication    0.003929
numerical_pipeline__referral_source_STMW         0.001783
numerical_pipeline__hypopituitary                0.000623
numerical_pipeline__lithium                      0.000000
dtype: float64

In [144]:
X.drop(labels=['referral_source_STMW',
'referral_source_SVI',
'query_hyperthyroid',
'referral_source_SVHD',
'query_on_thyroxine',         
'on_antithyroid_medication',    
'thyroid_surgery',              
'hypopituitary',                                        
'lithium',                  
'tumor'],axis=1,inplace=True)

In [145]:
X.head()

,age,sex,on_thyroxine,sick,pregnant,I131_treatment,query_hypothyroid,goitre,psych,TSH,T3,TT4,T4U,FTI,referral_source_SVHC,referral_source_other
0,41.0,0.0,0,0,0,0,0,0,0,1.3,2.5,125,1.14,109,True,False
1,23.0,0.0,0,0,0,0,0,0,0,4.1,2,102,NaN,NaN,False,True
2,46.0,1.0,0,0,0,0,0,0,0,0.98,NaN,109,0.91,120,False,True
3,70.0,0.0,1,0,0,0,0,0,0,0.16,1.9,175,NaN,NaN,False,True
4,70.0,0.0,0,0,0,0,0,0,0,0.72,1.2,61,0.87,70,False,False

In [146]:
X.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13924 entries, 0 to 13923
Data columns (total 16 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   age                    13923 non-null  float64
 1   sex                    13496 non-null  float64
 2   on_thyroxine           13924 non-null  int64
 3   sick                   13924 non-null  int64
 4   pregnant               13924 non-null  int64
 5   I131_treatment         13924 non-null  int64
 6   query_hypothyroid      13924 non-null  int64
 7   goitre                 13924 non-null  int64
 8   psych                  13924 non-null  int64
 9   TSH                    13555 non-null  object
 10  T3                     12189 non-null  object
 11  TT4                    13553 non-null  object
 12  T4U                    11290 non-null  object
 13  FTI                    11292 non-null  object
 14  referral_source_SVHC   13924 non-null  bool
 15  referral_source_other  13924 non-null  bool
dtypes: bool(2), float64(2), int64(7), object(5)
memory usage: 1.5+ MB

In [147]:
categorical_columns =X.columns[X.dtypes=='O']
numerical_columns=X.columns[X.dtypes!='O']

In [148]:
numerical_columns

Index(['age', 'sex', 'on_thyroxine', 'sick', 'pregnant', 'I131_treatment',
       'query_hypothyroid', 'goitre', 'psych', 'referral_source_SVHC',
       'referral_source_other'],
      dtype='object')

In [149]:
categorical_columns

Index(['TSH', 'T3', 'TT4', 'T4U', 'FTI'], dtype='object')

In [150]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.30,random_state=42)

In [151]:
numerical_pipeline=Pipeline(
    steps=[
        ('imputer', SimpleImputer(strategy='mean')),
        ('scaler', StandardScaler()),
        


    ]
)
categorical_pipeline=Pipeline(
    steps=[
        ('imputer',SimpleImputer(strategy='most_frequent')),
        ('scaler',StandardScaler()),
        

    ]
)

In [152]:
preprocessor=ColumnTransformer(
    transformers=[
        ('numerical_pipeline',numerical_pipeline,numerical_columns),
        ('categorical_pipeline',categorical_pipeline,categorical_columns)
    ]
)

In [153]:
X_train=pd.DataFrame(preprocessor.fit_transform(X_train),columns=preprocessor.get_feature_names_out())

In [154]:
X_test=pd.DataFrame(preprocessor.transform(X_test),columns=preprocessor.get_feature_names_out())

In [71]:
X_train.head()

,numerical_pipeline__age,numerical_pipeline__sex,numerical_pipeline__on_thyroxine,numerical_pipeline__sick,numerical_pipeline__pregnant,numerical_pipeline__I131_treatment,numerical_pipeline__query_hypothyroid,numerical_pipeline__goitre,numerical_pipeline__psych,numerical_pipeline__referral_source_SVHC,numerical_pipeline__referral_source_other,categorical_pipeline__TSH,categorical_pipeline__T3,categorical_pipeline__TT4,categorical_pipeline__T4U,categorical_pipeline__FTI
0,-2.723189,-0.700238,-0.243614,-0.153727,-0.065788,-0.117624,-0.510848,-0.049685,-0.157189,-0.215625,-1.474300,-0.306181,-0.508345,-0.468234,-0.486239,-0.498683
1,0.508367,-0.700238,-0.243614,-0.153727,-0.065788,-0.117624,1.957531,-0.049685,-0.157189,-0.215625,0.678288,-0.140768,0.663217,0.022250,0.650084,-0.247929
2,0.623779,1.471417,-0.243614,-0.153727,-0.065788,-0.117624,-0.510848,-0.049685,-0.157189,-0.215625,-1.474300,0.122723,-1.289386,-1.081339,-1.742175,-1.055913
3,-0.934292,-0.700238,-0.243614,-0.153727,-0.065788,-0.117624,1.957531,-0.049685,-0.157189,-0.215625,0.678288,-0.170044,0.142523,0.193919,-0.486239,-0.498683
4,-0.472641,1.471417,-0.243614,-0.153727,-0.065788,-0.117624,1.957531,-0.049685,-0.157189,-0.215625,0.678288,-0.404039,1.183912,-1.105863,-0.486239,-0.498683

In [72]:

from sklearn.tree import DecisionTreeClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.metrics import accuracy_score
from sklearn.neighbors import KNeighborsClassifier

In [73]:
models={
    'randomforestclassifirer':RandomForestClassifier(),
    'DecisionTreeClassifier':DecisionTreeClassifier(),
    'Logisticregression':LogisticRegression(),
    'svc':SVC(),

}

In [74]:
# evaluate_model(X_train,y_train,X_test,y_test,models)

In [75]:
def evaluate_model(true,pred):
    accuracy=accuracy_score(true,pred)
    return accuracy

In [76]:
model_list=[]
test_model=[]
r2_list=[]
for i in range(len(list(models))):
     model=list(models.values())[i]
     model.fit(X_train, y_train)
     y_pred=model.predict(X_test)
     accuracy=evaluate_model(y_test,y_pred)
     print(list(models.values())[i])
     model_list.append(list(models.values())[i])
     print('Model training performance')
     print('Accuracy',accuracy)
     r2_list.append(accuracy)
     print("="*35)

RandomForestClassifier()
Model training performance
Accuracy 0.9985639061752034
===================================
DecisionTreeClassifier()
Model training performance
Accuracy 0.9985639061752034
===================================
LogisticRegression()
Model training performance
Accuracy 0.974150311153662
===================================
SVC()
Model training performance
Accuracy 0.9372905696505505
===================================